replicaCount: 3


image:
  repository: "us-central1-docker.pkg.dev/adroit-router-411501/artemis/artemis"
  tag: "2.0.0"


service:
  type: ClusterIP
  port: 5000


ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

  hosts:
    - host: dev-artemis.ground-breaker.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: dev-artemis-tls
     hosts:
       - dev-artemis.ground-breaker.com
